# -*- coding: utf-8 -*-
"""TuBes_PDAipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBkxl01pCWgPNqO7q3r7-S2qLbRDQg3h

#Menginstall kaggle dan meng-import Dataset
"""

pip install kaggle

from google.colab import files

files.upload()

"""Upload Kaggle.json untuk menggunakan Kaggle"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d shwetabh123/mall-customers

import zipfile
import os

for file in os.listdir():
     if file.endswith('.zip'):
         zip_ref = zipfile.ZipFile(file, 'r')
         zip_ref.extractall()
         zip_ref.close()

import pandas as pd

df = pd.read_csv('Mall_Customers.csv')
df.head()

df.shape

df.describe().T

df.info()

df.isna().sum()

"""# Visualization"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the original data as requested by the user
df = pd.read_csv('Mall_Customers.csv')

# 1. Histogram for Spending Score
plt.figure(figsize=(10, 6))
sns.histplot(df['Spending Score (1-100)'], bins=10, kde=True)
plt.title('Distribution of Spending Score')
plt.xlabel('Spending Score (1-100)')
plt.ylabel('Frequency')
plt.show()

# 2. Scatter Plot between Annual Income and Spending Score
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Annual Income (k$)', y='Spending Score (1-100)', data=df)
plt.title('Annual Income vs. Spending Score')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.show()

# 3. Boxplot of Spending Score by Gender
plt.figure(figsize=(8, 6))
sns.boxplot(x='Genre', y='Spending Score (1-100)', data=df)
plt.title('Spending Score by Gender')
plt.xlabel('Gender')
plt.ylabel('Spending Score (1-100)')
plt.show()

plt.figure(figsize=(10, 6))
plt.hist(df['Age'], bins=20, edgecolor='black')
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

for i in df.columns:
  plt.figure(figsize=(10, 6))
  sns.boxplot(df[i])
  plt.title(f'Boxplot of {i}')
  plt.show()

"""#Preprocessing

#Remove Outliers
"""

q1 = df.quantile(0.25, numeric_only=True)
q3 = df.quantile(0.75, numeric_only=True)
iqr = q3 - q1

for col in df.select_dtypes(include=['int64', 'float64']).columns:
    lower_bound = q1[col] - 1.5 * iqr[col]
    upper_bound = q3[col] + 1.5 * iqr[col]
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

print(f"DataFrame shape after outlier removal: {df.shape}")

"""#Embedding and removing unnecesary columns"""

df.drop(['CustomerID'], axis=1, inplace=True)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Genre'] = le.fit_transform(df['Genre'])

df.head()

y = df['Spending Score (1-100)']
X = df.drop(['Spending Score (1-100)'], axis=1)

"""#Splitting data"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""# Machine Learning

# Linear Regression
"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

lr = LinearRegression()

lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

"""# Hyperparameter Tuning"""

from sklearn.model_selection import GridSearchCV

param_grid = {
    'fit_intercept': [True, False],
    'n_jobs': [-1, None],
    'positive': [True, False],
    'copy_X': [True, False]
}

grid_search = GridSearchCV(lr, param_grid, cv=5)
grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
best_score = grid_search.best_score_

print(f"Best Hyperparameters: {best_params}")
print(f"Best Cross-Validation Score: {best_score:.4f}")

lr_hp = LinearRegression(**best_params)

lr_hp.fit(X_train, y_train)

y_pred_hp = lr_hp.predict(X_test)
mae_hp = mean_absolute_error(y_test, y_pred_hp)
mse_hp = mean_squared_error(y_test, y_pred_hp)
r2_hp = r2_score(y_test, y_pred_hp)

print(f"Mean Absolute Error after hyperparameter tuning: {mae_hp:.2f}")
print(f"Mean Squared Error after hyperparameter tuning: {mse_hp:.2f}")
print(f"R-squared (R2) after hyperparameter tuning: {r2_hp:.2f}")